import { NextUiProvider } from "@/components/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "next-admin",
  description: "Generated by create next app",
  authors: [{ name: "马旭", url: "https://github.com/silent-mx" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hans">
      <head>
        <meta name="company-name" content="中国电信股份有限公司昭通分公司"></meta>
        <meta name="company-address" content="云南省昭通市昭阳区公园路88号"></meta>
      </head>
      <body className={inter.className}>
        <NextUiProvider>{children}</NextUiProvider>
      </body>
    </html>
  );
}
